# Generated by Django 3.0.4 on 2020-10-03 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessagingSystem', '0006_message_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='receiver',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.CharField(max_length=50),
        ),
    ]
