# Generated by Django 3.0.4 on 2020-10-04 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessagingSystem', '0009_auto_20201003_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
